applications:
  - glance
classes:
- system.linux.system.container
- system.openstack.common.cluster
parameters:
  _param:
    single_address: 127.0.0.1
  linux:
    system:
      name: glance-server
  glance:
    server:
      enabled: true
      version: ${_param:glance_version}
      workers: 1
      database:
        engine: mysql
        host: "$MYSQL_SERVER_SERVICE_HOST"
        port: "$MYSQL_SERVER_SERVICE_PORT"
        name: glance
        user: glance
        password: ${_param:mysql_glance_password}
      rabbit:
        host: "$RABBITMQ_SERVER_NODE01_SERVICE_HOST"
      registry:
        host: 127.0.0.1
        port: 9191
      bind:
        address: 0.0.0.0
        port: 9292
      identity:
        engine: keystone
        host: "$KEYSTONE_SERVER_SERVICE_HOST"
        port: 35357
        user: glance
        password: ${_param:keystone_glance_password}
        tenant: service
      message_queue:
        engine: rabbitmq
        host: "$RABBITMQ_SERVER_NODE01_SERVICE_HOST"
        port: "$RABBITMQ_SERVER_NODE01_SERVICE_PORT"
        user: openstack
        password: ${_param:rabbitmq_openstack_password}
        virtual_host: '/openstack'
      storage:
        engine: file
      cache:
        engine: memcached
        members:
          - host: "$MEMCACHED_SERVER_NODE01_SERVICE_HOST"
            port: "$MEMCACHED_SERVER_NODE01_SERVICE_PORT"
          - host: "$MEMCACHED_SERVER_NODE02_SERVICE_HOST"
            port: "$MEMCACHED_SERVER_NODE02_SERVICE_PORT"
          - host: "$MEMCACHED_SERVER_NODE03_SERVICE_HOST"
            port: "$MEMCACHED_SERVER_NODE03_SERVICE_PORT"
