applications:
  - nova
classes:
- system.linux.system.container
- system.openstack.common.cluster
parameters:
  _param:
    single_address: 127.0.0.1
    nova_networking: contrail
  linux:
    system:
      name: nova-compute
  nova:
    compute:
      version: ${_param:nova_version}
      enabled: true
      virtualization: kvm
      vncproxy_url: http://vncproxy_url:6080
      reserved_host_memory_mb: 32768
      log_dir_perms: 755
      bind:
        vnc_address: "$NOVA_COMPUTE_LOCAL_HOST"
        vnc_port: 6080
        vnc_name: 0.0.0.0
      database:
        engine: mysql
        host: "$MYSQL_SERVER_SERVICE_HOST"
        port: "$MYSQL_SERVER_SERVICE_PORT"
        name: nova
        user: nova
        password: ${_param:mysql_nova_password}
      identity:
        engine: keystone
        host: "$KEYSTONE_SERVER_SERVICE_HOST"
        port: 35357
        user: nova
        password: ${_param:keystone_nova_password}
        tenant: service
      message_queue:
        engine: rabbitmq
        host: "$RABBITMQ_SERVER_NODE01_SERVICE_HOST"
        port: "$RABBITMQ_SERVER_NODE01_SERVICE_PORT"
        user: openstack
        password: ${_param:rabbitmq_openstack_password}
        virtual_host: '/openstack'
      image:
        engine: glance
        host: "$GLANCE_SERVER_SERVICE_HOST"
        port: 9292
      network:
        engine: neutron
        user: neutron
        password: ${_param:keystone_neutron_password}
        host: "$NEUTRON_SERVER_SERVICE_HOST"
        port: 9696
      cache:
        engine: memcached
        members:
          - host: "$MEMCACHED_SERVER_NODE01_SERVICE_HOST"
            port: "$MEMCACHED_SERVER_NODE01_SERVICE_PORT"
          - host: "$MEMCACHED_SERVER_NODE02_SERVICE_HOST"
            port: "$MEMCACHED_SERVER_NODE02_SERVICE_PORT"
          - host: "$MEMCACHED_SERVER_NODE03_SERVICE_HOST"
            port: "$MEMCACHED_SERVER_NODE03_SERVICE_PORT"