applications:
  - opencontrail
classes:
- system.linux.system.container
- system.openstack.common.cluster
parameters:
  _param:
    single_address: 127.0.0.1
  linux:
    system:
      name: "$HOSTNAME"
  opencontrail:
    common:
      version: ${_param:opencontrail_version}
      identity:
        engine: kubernetes
        password: none
        token: none
    control:
      version: ${_param:opencontrail_version}
      enabled: true
      bind:
        address: "$OPENCONTRAIL_CONTROL_LOCAL_HOST"
      discovery:
        host: "$OPENCONTRAIL_CONFIG_SERVICE_HOST"
      members:
      - host: "$OPENCONTRAIL_DATABASE_SERVICE_HOST"
        id: 1