applications:
  - opencontrail
classes:
- system.linux.system.container
- system.openstack.common.cluster
parameters:
  _param:
    single_address: 127.0.0.1
  linux:
    system:
      name: "$HOSTNAME"
  opencontrail:
    common:
      version: ${_param:opencontrail_version}
      identity:
        engine: kubernetes
        token: none
        password: none
    collector:
      version: ${_param:opencontrail_version}
      enabled: true
      bind:
        address: "$OPENCONTRAIL_COLLECTOR_LOCAL_HOST"
      discovery:
        host: "$OPENCONTRAIL_CONFIG_SERVICE_HOST"
      data_ttl: 1
      database:
        members:
        - host: "$OPENCONTRAIL_DATABASE_SERVICE_HOST"
          port: 9160
#        - host: ${_param:cluster_node02_address}
#          port: 9160
#        - host: ${_param:cluster_node03_address}
#          port: 9160