applications:
  - opencontrail
classes:
- system.linux.system.container
- system.openstack.common.cluster
parameters:
  _param:
    single_address: 127.0.0.1
  linux:
    system:
      name: "$HOSTNAME"
  opencontrail:
    common:
      version: ${_param:opencontrail_version}
      identity:
        engine: kubernetes
        password: none
        token: none
    config:
      version: ${_param:opencontrail_version}
      enabled: true
      multi_tenancy: false
      discovery:
        host: "$OPENCONTRAIL_CONFIG_LOCAL_HOST"
      analytics:
        host: "$OPENCONTRAIL_COLLECTOR_SERVICE_HOST"
      bind:
        address: 0.0.0.0
      message_queue:
        engine: rabbitmq
        host: "$RABBITMQ_SERVER_NODE01_SERVICE_HOST"
        port: "$RABBITMQ_SERVER_NODE01_SERVICE_PORT"
      database:
        members:
        - host: "$OPENCONTRAIL_DATABASE_SERVICE_HOST"
          port: 9160
#        - host: ${_param:cluster_node02_address}
#          port: 9160
#        - host: ${_param:cluster_node03_address}
#          port: 9160
      identity:
        engine: kubernetes
        password: none
        token: none
      members:
      - host: "$OPENCONTRAIL_CONTROL_SERVICE_HOST"
        id: 1
#      - host: ${_param:cluster_node02_address}
#        id: 2
#      - host: ${_param:cluster_node03_address}
#        id: 3
